### PR TITLE
feat: added dependabot - auto dependecies update

### PR DESCRIPTION
**Pull request by mmornati**
# Dependencies Management

## Why?
To prevent security breach it is better to have a project always up to dates. With [DependaBot](https://dependabot.com/), now part of the GitHub family, the updates come to you without the need to take time to check for them.
image

## What?
The proposed configuration is taking care of all possible updates in the Java part of the project and only to the *security* updates for the NPM part. 
Configuration can be naturally changed as desired.

### CODE REVIEW

**Comment by mmornati** [comment]
@dktsni do you need this pullrequest on v4 too instead of master? Don't know if you are using dependabot but it is opening PR when a new version of lib you are using (npm or maven) is available.

**Comment by dktsni** [comment]
Hi @mmornati 
Dependabot was already added on version 4.0.0 (thx to @lusoalex ), you can find its configuration [here](https://github.com/Decathlon/ara/blob/version/4.0.0/.dependabot/config.yml) :) 

Master isn't subject to changes (unless a Hotfix on the current version is needed), so I think that we can skip Dependabot on it (cf discussions on PR #116 )

Thanks !

**Comment by lusoalex** [comment]
@dktsni can you close the PR? ;)

**Comment by lusoalex** [comment]
@dktsni @mmornati As dependabot was already added previously, this PR has been closed, but the branch has not been deleted. Could one of you delete it?
Regards,
Alexandre.

**Comment by dktsni** [comment]
Done ;)

**Pull request closed without merging**
