### PR TITLE
feat: circle-ci build proposal

### PR DESCRIPTION
**Pull request by mmornati**

### CODE REVIEW

**Comment by dktsni** [comment]
Hi @mmornati !

Thanks for this work and your interest on ARA :D 

Unfortunately, the master branch doesn't build so "easy", it will needs a database up and running to build (due to the querydsl and liquibase plugins in the ara-server pom.xml). That's why for now their is no CI on the master branch.

However, those constraints are in the process of being removed in the version 4.0.0 (see https://github.com/Decathlon/ara/projects/1 for more details), and we could definitely use your work ! Could you please update your PR to make the base branch `version/4.0.0` instead of `master` ?

Thanks again !

**Comment by mmornati** [comment]
Thanks for your reply @dktsni. I just moved to the correct branch.
About version 4 @lusoalex gave me the information yesterday evening, but I decided to create the PR instead of simply open a new issue. I prefer to propose code instead of idea 📦 

I will try during the day to use circle-ci on the v4 branch.

**Comment by dktsni** [comment]
Thanks for your actions ! 
I'll wait for your tests to review this PR ;)

**Comment by mmornati** [comment]
@dktsni it seems the build is failing on some tests (even if the VM is exposing without a lot of details): https://circleci.com/gh/Decathlon/ara/4

image

I tried to execute the build locally but I've a problem on the JavaDoc:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project ara-lib: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR]
[ERROR] Command line was: /Users/Marco/.sdkman/candidates/java/current/bin/javadoc @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/Users/Marco/Projects/ara/lib/target/apidocs' dir.
[ERROR]
[ERROR] -> [Help 1]
```

Do I have to use only the JDK 8 for build or a future version should work?

**Comment by dktsni** [comment]
Hi @mmornati 

Unfortunately, ARA supports only Java 8 for now (but it will be upgraded later).

I'm currently on the Tests resolutions, I'll keep you in touch when the fix is merged on version/4.0.0

**Comment by dktsni** [comment]
Hi @mmornati !

Tests are fixed on the branch `version/4.0.0` now. You can rebase it and continue your (awesome) work on the integration of CircleCI to ARA if you want ! 

(Or I can do it if you don't have the time / will to do it anymore :) )

**Comment by mmornati** [comment]
Hey @dktsni... sorry for the delay. I was on holiday without my laptop :)

I can take care to it or even wait and directly migrate to the GitHub CI? We have no access yet on the Decathlon OpenSource repository (we asked to be part of the beta several months ago). The final release of the GitHub CI (officially open to anyone) will be in November 2019.

I let you the final decision about what to use to build the project.

If you want to have a look to the CI I started using it on a personal OSS project: https://github.com/mmornati/docker-ghostblog/pull/53

https://github.com/mmornati/docker-ghostblog/pull/53/checks?check_run_id=196528855

It is quite easy too 👍

**Comment by dktsni** [comment]
Hi @mmornati 

No problem for the delay ;) 

Unfortunately we can't wait for the GithubCI, the version 4.0.0 is quite expected by some teams :) 

I've just fix the CircleCI pipeline, I'll update it with some (pre/post)release mechanism and I'll merge it today :) 

Thanks for your work anyway :D

**Comment by lusoalex** [comment]
Hello, I have updated the configuration to use CircleCi env var required by the docker login, in order to push on dockher hub...

**Comment by lusoalex** [comment]
Sorry for the delay, that's ok now, I managed docker login with this #141 PR.
Regards,
Alex.

**Pull request merged**
